process_names:
  # comm is the second field of /proc/<pid>/stat minus parens.
  # It is the base executable name, truncated at 15 chars.
  # It cannot be modified by the program, unlike exe.
  - name: "{{.ExeFull}}:{{.Matches.appname}}"
    exe:
      - dotnet
    cmdline:
      - dotnet(?P<appname>.*?)dotnet

extra_labels:
  environment: test
  team: it
